import { existsSync, readFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { assetsDir } from '../common/assets';
import { SeedEntity } from '../common/entity';
import { DOCUMENT_TYPES, FileStore, IMAGE_TYPES } from './file-store.service';
import { PatientDocument, PatientPhoto } from './history.entity';

/**
 * Sample photos and signed forms for the demo patients, generated by
 * scripts/generate-demo-assets.mjs into assets/demo/. Loaded only with SEED_DEMO_DATA=true.
 */
type Manifest = {
  photos: (Omit<PatientPhoto, 'id' | 'createdAt' | 'updatedAt' | 'file'> & {
    file: string;
  })[];
  documents: (Omit<
    PatientDocument,
    'id' | 'createdAt' | 'updatedAt' | 'file'
  > & { file: string })[];
};

function manifest(): Manifest | null {
  if (process.env.SEED_DEMO_DATA !== 'true') return null;
  const path = join(assetsDir(), 'demo', 'manifest.json');
  return existsSync(path)
    ? (JSON.parse(readFileSync(path, 'utf8')) as Manifest)
    : null;
}

function load(files: FileStore, file: string, allowed: string[]) {
  const buffer = readFileSync(join(assetsDir(), 'demo', file));
  return files.save(
    {
      originalname: basename(file),
      mimetype: '',
      size: buffer.length,
      buffer,
    },
    allowed,
  );
}

const hoursAfter = (iso: string, h: number) =>
  new Date(new Date(iso).getTime() + h * 3_600_000).toISOString();

export function demoPhotos(files: FileStore): SeedEntity<PatientPhoto>[] {
  return (manifest()?.photos ?? []).map(({ file, ...p }, i) => ({
    ...p,
    id: `PH-${i + 1}`,
    // Uploaded the evening of the day they were taken (IST).
    createdAt: new Date(`${p.takenOn}T18:00:00+05:30`).toISOString(),
    file: load(files, file, IMAGE_TYPES),
  }));
}

export function demoDocuments(files: FileStore): SeedEntity<PatientDocument>[] {
  return (manifest()?.documents ?? []).map(({ file, ...d }, i) => ({
    ...d,
    id: `DOC-${i + 1}`,
    createdAt: hoursAfter(d.signedAt, 2),
    file: load(files, file, DOCUMENT_TYPES),
  }));
}
